"""FIR-style case report (PDF).

Laid out like the numbered sections of an Indian First Information Report so
the printout reads like a police case file: station and FIR details,
occurrence, complainant, accused (with photos when on file), victims,
evidence with integrity hashes, brief facts, investigation status, the AI
decision-support record with its human review, and signature blocks.

It is a case-file printout generated by a demonstration system, not a legal
FIR form, and says so on every page.
"""
from __future__ import annotations

import io
from datetime import datetime, timezone
from typing import Any, Iterable, Optional

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib.utils import ImageReader
from reportlab.platypus import (
    BaseDocTemplate, Frame, Image, KeepTogether, PageTemplate, Paragraph, Spacer, Table, TableStyle,
)
from xml.sax.saxutils import escape

from app.constants import LOCATION_TYPES, MODUS_OPERANDI, TARGET_TYPES

INK = colors.HexColor("#0E1524")
KHAKI = colors.HexColor("#A8751B")
RULE = colors.HexColor("#C9CED8")
SHADE = colors.HexColor("#F2F3F6")
MUTED = colors.HexColor("#5B6475")
RED = colors.HexColor("#B42318")
AMBER_BG = colors.HexColor("#FFF4E0")

PAGE_W, PAGE_H = A4
MARGIN = 1.8 * cm
CONTENT_W = PAGE_W - 2 * MARGIN

_styles = {
    "body": ParagraphStyle("body", fontName="Helvetica", fontSize=9, leading=12.5, textColor=INK),
    "small": ParagraphStyle("small", fontName="Helvetica", fontSize=7.5, leading=10, textColor=MUTED),
    "label": ParagraphStyle("label", fontName="Helvetica", fontSize=7, leading=9, textColor=MUTED),
    "value": ParagraphStyle("value", fontName="Helvetica-Bold", fontSize=9, leading=12, textColor=INK),
    "mono": ParagraphStyle("mono", fontName="Courier", fontSize=7.5, leading=9.5, textColor=INK),
    "section": ParagraphStyle("section", fontName="Helvetica-Bold", fontSize=10.5, leading=14, textColor=INK,
                              spaceBefore=10, spaceAfter=4),
    "title": ParagraphStyle("title", fontName="Helvetica-Bold", fontSize=15, leading=19, textColor=INK),
    "cell": ParagraphStyle("cell", fontName="Helvetica", fontSize=8, leading=10.5, textColor=INK),
    "cellb": ParagraphStyle("cellb", fontName="Helvetica-Bold", fontSize=8, leading=10.5, textColor=INK),
    "notice": ParagraphStyle("notice", fontName="Helvetica", fontSize=8, leading=11, textColor=INK),
    "center": ParagraphStyle("center", fontName="Helvetica", fontSize=8, leading=11, textColor=MUTED,
                             alignment=TA_CENTER),
}


def _p(text: Any, style: str = "body") -> Paragraph:
    return Paragraph(escape("" if text is None else str(text)).replace("\n", "<br/>"), _styles[style])


def _v(value: Any, fallback: str = "Not recorded") -> str:
    if value is None or value == "":
        return fallback
    if isinstance(value, bool):
        return "Yes" if value else "No"
    return str(value)


def _date(value: Any, with_time: bool = False) -> str:
    if not value:
        return "Not recorded"
    if isinstance(value, datetime):
        return value.strftime("%d %b %Y, %H:%M" if with_time else "%d %b %Y")
    text = str(value)
    try:
        parsed = datetime.fromisoformat(text.replace("Z", "+00:00"))
        return parsed.strftime("%d %b %Y, %H:%M" if with_time else "%d %b %Y")
    except ValueError:
        return text[:16] if with_time else text[:10]


def _pct(value: Any) -> str:
    try:
        number = float(value or 0)
    except (TypeError, ValueError):
        return "N/A"
    return f"{number * 100 if number <= 1 else number:.1f}%"


def _section(number: int, title: str) -> Table:
    t = Table([[_p(f"{number}.", "section"), _p(title.upper(), "section")]], colWidths=[0.8 * cm, CONTENT_W - 0.8 * cm])
    t.setStyle(TableStyle([
        ("LINEBELOW", (0, 0), (-1, 0), 0.8, INK),
        ("LEFTPADDING", (0, 0), (-1, -1), 0), ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
        ("VALIGN", (0, 0), (-1, -1), "BOTTOM"),
    ]))
    return t


def _fields(pairs: Iterable[tuple], columns: int = 3) -> Table:
    """Label-over-value grid, like the boxes of a printed form."""
    cells = [[_p(label, "label"), _p(value, "value")] for label, value in pairs]
    rows = []
    for i in range(0, len(cells), columns):
        chunk = cells[i:i + columns]
        chunk += [["", ""]] * (columns - len(chunk))
        rows.append([Table([[c[0]], [c[1]]], colWidths=[CONTENT_W / columns - 8]) if c[0] else "" for c in chunk])
    t = Table(rows, colWidths=[CONTENT_W / columns] * columns)
    t.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.4, RULE),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 4), ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 2), ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))
    return t


def _grid(header: list, rows: list, widths: list) -> Table:
    data = [[_p(h, "cellb") for h in header]] + [
        [c if isinstance(c, (Paragraph, Image, Table, list)) else _p(c, "cell") for c in r] for r in rows]
    t = Table(data, colWidths=widths, repeatRows=1)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), SHADE),
        ("LINEBELOW", (0, 0), (-1, 0), 0.8, INK),
        ("LINEBELOW", (0, 1), (-1, -1), 0.4, RULE),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 4), ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 3), ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))
    return t


def _none(text: str) -> Paragraph:
    return _p(text, "small")


def _seal(canvas, x: float, y: float, r: float) -> None:
    """Circular station-style seal drawn in vector, so no image asset is needed."""
    canvas.saveState()
    canvas.setStrokeColor(KHAKI)
    canvas.setFillColor(KHAKI)
    canvas.setLineWidth(1.4)
    canvas.circle(x, y, r)
    canvas.setLineWidth(0.6)
    canvas.circle(x, y, r - 3)
    canvas.setFont("Helvetica-Bold", r * 0.42)
    canvas.drawCentredString(x, y - r * 0.15, "CR")
    canvas.setFont("Helvetica", r * 0.16)
    canvas.drawCentredString(x, y + r * 0.42, "AI-CRMS")
    canvas.drawCentredString(x, y - r * 0.62, "RECORDS")
    canvas.restoreState()


def _decorate(case: dict):
    case_no = _v(case.get("case_number"), "")
    fir_no = _v(case.get("fir_number"), "")
    generated = datetime.now(timezone.utc).strftime("%d %b %Y %H:%M UTC")
    by = _v(case.get("generated_by"), "")

    def draw(canvas, doc):
        canvas.saveState()
        top = PAGE_H - MARGIN + 0.9 * cm
        # Running header
        _seal(canvas, MARGIN + 0.55 * cm, top - 0.25 * cm, 0.55 * cm)
        canvas.setFillColor(INK)
        canvas.setFont("Helvetica-Bold", 9)
        canvas.drawString(MARGIN + 1.35 * cm, top, "AI-CRMS  |  CASE FILE  -  FIR-STYLE REPORT")
        canvas.setFont("Helvetica", 7.5)
        canvas.setFillColor(MUTED)
        canvas.drawString(MARGIN + 1.35 * cm, top - 0.38 * cm, f"{case_no}   {fir_no}")
        canvas.setFillColor(RED)
        canvas.setFont("Helvetica-Bold", 8)
        canvas.drawRightString(PAGE_W - MARGIN, top, "CONFIDENTIAL")
        canvas.setStrokeColor(INK)
        canvas.setLineWidth(0.8)
        canvas.line(MARGIN, top - 0.7 * cm, PAGE_W - MARGIN, top - 0.7 * cm)
        # Footer
        canvas.setStrokeColor(RULE)
        canvas.setLineWidth(0.4)
        canvas.line(MARGIN, MARGIN - 0.5 * cm, PAGE_W - MARGIN, MARGIN - 0.5 * cm)
        canvas.setFont("Helvetica", 6.8)
        canvas.setFillColor(MUTED)
        canvas.drawString(MARGIN, MARGIN - 0.85 * cm,
                          f"Generated {generated} by {by}. Demonstration system: not a legal FIR. For official use only.")
        canvas.drawRightString(PAGE_W - MARGIN, MARGIN - 0.85 * cm, f"Page {doc.page}")
        canvas.restoreState()

    return draw


def _photo(data: Optional[bytes], size: float) -> Any:
    if not data:
        box = Table([[_p("NO PHOTO", "center")]], colWidths=[size], rowHeights=[size * 1.25])
        box.setStyle(TableStyle([("BOX", (0, 0), (-1, -1), 0.4, RULE), ("BACKGROUND", (0, 0), (-1, -1), SHADE),
                                 ("VALIGN", (0, 0), (-1, -1), "MIDDLE")]))
        return box
    try:
        reader = ImageReader(io.BytesIO(data))
        w, h = reader.getSize()
        scale = min(size / w, size * 1.25 / h)
        return Image(io.BytesIO(data), width=w * scale, height=h * scale)
    except Exception:  # an unreadable image must not break the whole report
        return _photo(None, size)


def generate_case_report(case: dict) -> bytes:
    buffer = io.BytesIO()
    doc = BaseDocTemplate(buffer, pagesize=A4, leftMargin=MARGIN, rightMargin=MARGIN,
                          topMargin=MARGIN + 0.6 * cm, bottomMargin=MARGIN,
                          title=f"Case report {case.get('case_number', '')}", author="AI-CRMS")
    frame = Frame(MARGIN, MARGIN, CONTENT_W, PAGE_H - 2 * MARGIN - 0.6 * cm, id="body", leftPadding=0, rightPadding=0)
    doc.addPageTemplates([PageTemplate(id="page", frames=[frame], onPage=_decorate(case))])
    story: list = []

    # Title block
    status = _v(case.get("status"), "unknown").replace("_", " ").upper()
    priority = _v(case.get("priority"), "normal").upper()
    title = Table([[
        [_p(case.get("title") or "Untitled case", "title"),
         _p(f"{_v(case.get('crime_type'), 'Offence not classified')}  |  {_v(case.get('location'), 'Location not recorded')}", "small")],
        Table([[_p("STATUS", "label")], [_p(status, "value")], [_p("PRIORITY", "label")], [_p(priority, "value")]],
              colWidths=[3.4 * cm]),
    ]], colWidths=[CONTENT_W - 3.6 * cm, 3.6 * cm])
    title.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "TOP"), ("LEFTPADDING", (0, 0), (-1, -1), 0),
                               ("BOX", (1, 0), (1, 0), 0.6, INK), ("LEFTPADDING", (1, 0), (1, 0), 6)]))
    story += [title, Spacer(1, 6)]

    n = 0

    def section(name: str):
        nonlocal n
        n += 1
        story.append(Spacer(1, 8))
        story.append(_section(n, name))
        story.append(Spacer(1, 4))

    section("Police station and FIR")
    story.append(_fields([
        ("Police station", _v(case.get("fir_station"))),
        ("FIR number", _v(case.get("fir_number"))),
        ("FIR date", _date(case.get("fir_date"))),
        ("Case number", _v(case.get("case_number"))),
        ("FIR recorded by", _v(case.get("fir_filed_by"))),
        ("Case opened", _date(case.get("created_at"))),
    ]))

    section("Occurrence of offence")
    story.append(_fields([
        ("Date and time of occurrence", _date(case.get("incident_date"), with_time=True)),
        ("Place of occurrence", _v(case.get("location"))),
        ("Offence", _v(case.get("crime_type"))),
        ("Weapon involved", _v(case.get("weapons_involved"))),
        ("Drugs involved", _v(case.get("drug_involvement"))),
        ("Financial motive", _v(case.get("financial_motivation"))),
        ("Type of place", _v(LOCATION_TYPES.get(case.get("location_type") or ""))),
        ("Target", _v(TARGET_TYPES.get(case.get("target_type") or ""))),
        ("Modus operandi", _v(MODUS_OPERANDI.get(case.get("modus_operandi") or ""))),
    ]))

    section("Complainant / informant")
    story.append(_fields([
        ("Name", _v(case.get("complainant_name"))),
        ("Contact", _v(case.get("complainant_contact"))),
        ("Technology used in offence", _v(case.get("tech_involvement"))),
    ]))

    section("Details of known / suspected accused")
    criminals = case.get("criminals") or []
    if criminals:
        rows = []
        for i, link in enumerate(criminals, 1):
            c = link.get("criminal", link)
            name = f"{c.get('first_name', '')} {c.get('last_name', '')}".strip()
            details = [_p(name, "cellb")]
            if c.get("alias"):
                details.append(_p(f"alias \"{c['alias']}\"", "small"))
            details.append(_p(_v(c.get('crn'), '-'), "mono"))
            flags = ", ".join(x for x in [
                "WANTED" if c.get("is_wanted") else "",
                "in custody" if c.get("is_incarcerated") else "",
                f"{c['gang_name']} ({c.get('gang_rank') or 'member'})" if c.get("gang_name") else "",
            ] if x)
            if flags:
                details.append(_p(flags, "small"))
            rows.append([str(i), _photo(c.get("photo_bytes"), 1.5 * cm), details,
                         _v(c.get("crime_type"), "-"), _v(link.get("role"), "suspect").title(),
                         _v(c.get("threat_level"), "-").title()])
        story.append(_grid(["#", "Photo", "Accused", "Primary offence", "Role", "Threat"], rows,
                           [0.7 * cm, 1.9 * cm, 6.2 * cm, 3.4 * cm, 1.8 * cm, CONTENT_W - 14 * cm]))
    else:
        story.append(_none("No accused persons are linked to this case."))

    section("Victims")
    victims = case.get("victims") or []
    if victims:
        story.append(_grid(["Name", "Age", "Gender", "Status", "Injuries"],
                           [[v.get("name"), _v(v.get("age"), "-"), _v(v.get("gender"), "-"),
                             _v(v.get("status"), "-").title(), _v(v.get("injury_description"), "-")] for v in victims],
                           [4.2 * cm, 1.2 * cm, 1.8 * cm, 2.4 * cm, CONTENT_W - 9.6 * cm]))
    else:
        story.append(_none("No victims recorded."))

    section("Property / evidence seized")
    evidence = case.get("evidence") or []
    if evidence:
        rows = []
        for e in evidence:
            integrity = [_p(f"SHA-256 {e['file_sha256']}", "mono")] if e.get("file_sha256") else [_p("No file hash", "small")]
            if e.get("file_name"):
                integrity.insert(0, _p(f"Stored file: {e['file_name']}", "small"))
            rows.append([_p(e.get("evidence_number"), "mono"), _v(e.get("type"), "-").title(),
                         [_p(e.get("description") or "-", "cell"),
                          _p(f"Collected by {_v(e.get('collected_by'), 'unknown')}", "small")] + integrity,
                         _v(e.get("status"), "-").replace("_", " ").title()])
        story.append(_grid(["Evidence no.", "Type", "Description and integrity", "Status"], rows,
                           [3.3 * cm, 2 * cm, CONTENT_W - 7.8 * cm, 2.5 * cm]))
    else:
        story.append(_none("No evidence recorded."))

    section("Brief facts of the case")
    story.append(_p(case.get("description") or "No summary recorded."))

    section("Investigation")
    story.append(_fields([
        ("Investigating officer", _v(case.get("officer_name"), "Unassigned")),
        ("Current status", status.title()),
        ("Closed on", _date(case.get("closed_at")) if case.get("closed_at") else "Open"),
    ]))

    predictions = case.get("ai_predictions")
    if predictions is not None:
        section("AI decision support and human review")
        notice = Table([[_p("Model outputs are unverified decision support produced by a model trained on synthetic "
                            "data. They are not evidence. Only the human review decision below is part of the record.",
                            "notice")]], colWidths=[CONTENT_W])
        notice.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, -1), AMBER_BG), ("LEFTPADDING", (0, 0), (-1, -1), 6),
                                    ("TOPPADDING", (0, 0), (-1, -1), 4), ("BOTTOMPADDING", (0, 0), (-1, -1), 5)]))
        story += [notice, Spacer(1, 4)]
        if predictions:
            rows = []
            for pr in predictions:
                decision = _v(pr.get("review_status"), "pending").upper()
                review = [_p(decision, "cellb")]
                if pr.get("reviewed_by"):
                    review.append(_p(f"by {pr['reviewed_by']}, {_date(pr.get('reviewed_at'))}", "small"))
                if pr.get("override_crime_type"):
                    review.append(_p(f"Override: {pr['override_crime_type']}", "small"))
                if pr.get("officer_remarks"):
                    review.append(_p(f"\"{pr['officer_remarks']}\"", "small"))
                rows.append([_v(pr.get("subject"), "-"), _date(pr.get("created_at")),
                             [_p(_v(pr.get("predicted_crime_type"), "-"), "cell"),
                              _p(f"score {_pct(pr.get('crime_type_confidence'))}", "small")],
                             f"{float(pr.get('risk_score') or 0):.0f}/100 ({_v(pr.get('risk_level'), '-')})", review])
            story.append(_grid(["Subject", "Generated", "Suggested offence", "Danger score", "Human review"], rows,
                               [3.2 * cm, 2.2 * cm, 3.4 * cm, 2.6 * cm, CONTENT_W - 11.4 * cm]))
        else:
            story.append(_none("No AI assessments have been run for this case or its accused."))

    # Signature blocks
    sign = Table([[
        [_p("Signature of investigating officer", "label"), Spacer(1, 26), _p(_v(case.get("officer_name"), ""), "value")],
        [_p("Signature of officer in charge, police station", "label"), Spacer(1, 26), _p("Name, rank and seal", "small")],
    ]], colWidths=[CONTENT_W / 2] * 2)
    sign.setStyle(TableStyle([("LINEABOVE", (0, 0), (-1, 0), 0.6, INK), ("VALIGN", (0, 0), (-1, -1), "TOP"),
                              ("LEFTPADDING", (0, 0), (-1, -1), 0), ("TOPPADDING", (0, 0), (-1, -1), 4)]))
    story += [Spacer(1, 18), KeepTogether([sign])]

    doc.build(story)
    return buffer.getvalue()
