"""baseline schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-02 22:04:11.489494
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gangs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('alias', sa.String(length=200), nullable=True),
    sa.Column('territory', sa.String(length=200), nullable=True),
    sa.Column('threat_level', sa.String(length=20), nullable=True),
    sa.Column('active_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('known_activities', sa.Text(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('gangs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gangs_id'), ['id'], unique=False)

    op.create_table('ml_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('precision_score', sa.Float(), nullable=True),
    sa.Column('recall_score', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('training_samples', sa.Integer(), nullable=True),
    sa.Column('feature_importances', sa.JSON(), nullable=True),
    sa.Column('evaluation_metadata', sa.JSON(), nullable=True),
    sa.Column('dataset_version', sa.String(length=50), nullable=True),
    sa.Column('evaluation_method', sa.String(length=120), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_models_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'investigating_officer', 'record_clerk', name='userrole'), nullable=False),
    sa.Column('badge_number', sa.String(length=20), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_action_created', ['action', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index('ix_audit_logs_resource', ['resource_type', 'resource_id'], unique=False)

    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('crime_type', sa.String(length=100), nullable=True),
    sa.Column('crime_category', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('incident_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('open', 'under_investigation', 'closed', 'archived', name='casestatus'), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('fir_number', sa.String(length=30), nullable=True),
    sa.Column('fir_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fir_filed_by', sa.String(length=100), nullable=True),
    sa.Column('fir_station', sa.String(length=100), nullable=True),
    sa.Column('complainant_name', sa.String(length=100), nullable=True),
    sa.Column('complainant_contact', sa.String(length=20), nullable=True),
    sa.Column('assigned_officer_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_officer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index('ix_cases_assigned_status', ['assigned_officer_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_cases_case_number'), ['case_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_cases_id'), ['id'], unique=False)
        batch_op.create_index('uq_cases_fir_number', ['fir_number'], unique=True)

    op.create_table('criminals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crn', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('alias', sa.String(length=200), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('fingerprint_id', sa.String(length=100), nullable=True),
    sa.Column('crime_type', sa.String(length=100), nullable=True),
    sa.Column('crime_category', sa.String(length=50), nullable=True),
    sa.Column('prior_convictions', sa.Integer(), nullable=True),
    sa.Column('modus_operandi', sa.Text(), nullable=True),
    sa.Column('known_associates', sa.Text(), nullable=True),
    sa.Column('gang_id', sa.Integer(), nullable=True),
    sa.Column('gang_rank', sa.String(length=50), nullable=True),
    sa.Column('is_wanted', sa.Boolean(), nullable=True),
    sa.Column('is_incarcerated', sa.Boolean(), nullable=True),
    sa.Column('threat_level', sa.String(length=20), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['gang_id'], ['gangs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('criminals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_criminals_crn'), ['crn'], unique=True)
        batch_op.create_index('ix_criminals_gang', ['gang_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_criminals_id'), ['id'], unique=False)
        batch_op.create_index('ix_criminals_wanted_risk', ['is_wanted', 'risk_score'], unique=False)

    op.create_table('password_recovery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('request_ip', sa.String(length=45), nullable=True),
    sa.Column('otp_hash', sa.String(length=64), nullable=False),
    sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('reset_token_hash', sa.String(length=64), nullable=True),
    sa.Column('reset_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reset_consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_recovery', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_recovery_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_recovery_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_recovery_request_ip'), ['request_ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_recovery_user_id'), ['user_id'], unique=False)

    op.create_table('system_settings',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_key'), ['key'], unique=False)

    op.create_table('ai_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criminal_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('predicted_crime_type', sa.String(length=100), nullable=True),
    sa.Column('crime_type_confidence', sa.Float(), nullable=True),
    sa.Column('gang_affiliation_probability', sa.Float(), nullable=True),
    sa.Column('predicted_gang_id', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('confidence_overall', sa.Float(), nullable=True),
    sa.Column('similar_criminals', sa.JSON(), nullable=True),
    sa.Column('similar_cases', sa.JSON(), nullable=True),
    sa.Column('input_features', sa.JSON(), nullable=True),
    sa.Column('review_status', sa.Enum('pending', 'confirmed', 'rejected', 'overridden', name='predictionstatus'), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('officer_remarks', sa.Text(), nullable=True),
    sa.Column('override_crime_type', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['criminal_id'], ['criminals.id'], ),
    sa.ForeignKeyConstraint(['predicted_gang_id'], ['gangs.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_predictions', schema=None) as batch_op:
        batch_op.create_index('ix_ai_predictions_case_created', ['case_id', 'created_at'], unique=False)
        batch_op.create_index('ix_ai_predictions_criminal_created', ['criminal_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_predictions_id'), ['id'], unique=False)

    op.create_table('case_criminals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('criminal_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['criminal_id'], ['criminals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'criminal_id', name='uq_case_criminal')
    )
    with op.batch_alter_table('case_criminals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_criminals_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_criminals_criminal_id'), ['criminal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_criminals_id'), ['id'], unique=False)

    op.create_table('criminal_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criminal_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('case_reference', sa.String(length=50), nullable=True),
    sa.Column('recorded_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['criminal_id'], ['criminals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('criminal_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_criminal_history_id'), ['id'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('evidence_number', sa.String(length=30), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location_found', sa.String(length=200), nullable=True),
    sa.Column('collected_by', sa.String(length=100), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('chain_of_custody', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'evidence_number', name='uq_case_evidence_number')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_id'), ['id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=30), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('target_role', sa.String(length=30), nullable=True),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('related_criminal_id', sa.Integer(), nullable=True),
    sa.Column('related_case_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['related_case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['related_criminal_id'], ['criminals.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)
        batch_op.create_index('ix_notifications_role_read', ['target_role', 'is_read'], unique=False)
        batch_op.create_index('ix_notifications_target_user_read', ['target_user_id', 'is_read'], unique=False)

    op.create_table('victims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('injury_description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('statement', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('victims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_victims_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('victims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_victims_id'))

    op.drop_table('victims')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_target_user_read')
        batch_op.drop_index('ix_notifications_role_read')
        batch_op.drop_index(batch_op.f('ix_notifications_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_case_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('criminal_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_criminal_history_id'))

    op.drop_table('criminal_history')
    with op.batch_alter_table('case_criminals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_criminals_id'))
        batch_op.drop_index(batch_op.f('ix_case_criminals_criminal_id'))
        batch_op.drop_index(batch_op.f('ix_case_criminals_case_id'))

    op.drop_table('case_criminals')
    with op.batch_alter_table('ai_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_predictions_id'))
        batch_op.drop_index('ix_ai_predictions_criminal_created')
        batch_op.drop_index('ix_ai_predictions_case_created')

    op.drop_table('ai_predictions')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_key'))

    op.drop_table('system_settings')
    with op.batch_alter_table('password_recovery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_recovery_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_recovery_request_ip'))
        batch_op.drop_index(batch_op.f('ix_password_recovery_id'))
        batch_op.drop_index(batch_op.f('ix_password_recovery_created_at'))

    op.drop_table('password_recovery')
    with op.batch_alter_table('criminals', schema=None) as batch_op:
        batch_op.drop_index('ix_criminals_wanted_risk')
        batch_op.drop_index(batch_op.f('ix_criminals_id'))
        batch_op.drop_index('ix_criminals_gang')
        batch_op.drop_index(batch_op.f('ix_criminals_crn'))

    op.drop_table('criminals')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index('uq_cases_fir_number')
        batch_op.drop_index(batch_op.f('ix_cases_id'))
        batch_op.drop_index(batch_op.f('ix_cases_case_number'))
        batch_op.drop_index('ix_cases_assigned_status')

    op.drop_table('cases')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_resource')
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index('ix_audit_logs_action_created')

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_models_id'))

    op.drop_table('ml_models')
    with op.batch_alter_table('gangs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gangs_id'))

    op.drop_table('gangs')
    # ### end Alembic commands ###
